name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run the API and Postman's tests
      run: | 
        npm run start &
        sleep 10
        newman run "api_test.json"

    #- name: Send email
    #  uses: devellany/send-mail@v1.0.2
    #  with:
    #      host: smtp.google.com
    #      account: ${{secrets.MAIL_ADDRESS}}
    #      password: ${{secrets.MAIL_PASSWORD}}
    #      sender: github
    #      from: ${{secrets.MAIL_ADDRESS}}
    #      subject: Github Actions job result
    #      body: file://README.md
    #      attachments: '[{"path":"README.md"}]'
    #      to: borostamas6@hotmail.com        





